# -*- coding: utf-8 -*-
"""tools_calling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YITQ9dfcbf0PVvGjh7QxAm_I-EPWfkh2
"""

import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyDwOA"

!pip install -q langchain-openai langchain-core requests

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests

# tool create

@tool
def multiply(a: int, b: int) -> int:
  """Given 2 numbers a and b this tool returns their product"""
  return a * b

print(multiply.invoke({'a':3, 'b':4}))

multiply.description

multiply.args

# tool bindinding
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

llm_with_tools=llm.bind_tools([multiply])

llm_with_tools.invoke("Hi how are you?")

query=HumanMessage("can you multiply 88 with 4 ")

message=[query]

message

result=llm_with_tools.invoke(message)

message.append(result)

result.tool_calls

tool_result=multiply.invoke(result.tool_calls[0])

tool_result

message.append(tool_result)

"""CURRENCY CONVERSION TOOl"""

from langchain_core.tools import InjectedToolArg
from typing import Annotated

# tool create
from langchain_core.tools import InjectedToolArg
from typing import Annotated

@tool
def get_conversion_factor(base_currency: str, target_currency: str) -> float:
  """
  This function fetches the currency conversion factor between a given base currency and a target currency
  """
  url = f'https://v6.exchangerate-api.com/v6/c754eab14ffab33112e380ca/pair/{base_currency}/{target_currency}'

  response = requests.get(url)

  return response.json()

@tool
def convert(base_currency_value: int, conversion_rate: Annotated[float, InjectedToolArg]) -> float:
  """
  given a currency conversion rate this function calculates the target currency value from a given base currency value
  """

  return base_currency_value * conversion_rate

convert.args

get_conversion_factor.invoke({'base_currency':'USD', 'target_currency':'INR'})

convert.invoke({'base_currency_value':100, 'conversion_rate':88.39})

# tool bindinding
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

llm_with_tool=llm.bind_tools([get_conversion_factor, convert])

messages = [HumanMessage('What is the conversion factor between INR and USD, and based on that can you convert 10 inr to usd')]

messages

ai_message=llm_with_tool.invoke(messages)

ai_message.tool_calls

import json
from langchain_core.messages import ToolMessage # Import ToolMessage

for tools in ai_message.tool_calls:
  if tools["name"]=="get_conversion_factor":
    tool_result_dict = get_conversion_factor.invoke(tools["args"])
    print(tool_result_dict)

    # fecting the conversion rate
    conversion_rate=tool_result_dict['conversion_rate']

    # Wrap the dictionary result in a ToolMessage
    tool_message1 = ToolMessage(content=json.dumps(tool_result_dict), tool_call_id=tools.get("id")) # Use tool_call_id

    # append
    messages.append(tool_message1)

  elif tools["name"]=="convert":
    tool_result_value = convert.invoke({'base_currency_value':10, 'conversion_rate':conversion_rate})
    print(tool_result_value)

    # Wrap the result in a ToolMessage
    tool_message2 = ToolMessage(content=str(tool_result_value), tool_call_id=tools.get("id")) # Use tool_call_id
    messages.append(tool_message2)

messages

