# -*- coding: utf-8 -*-
"""AI-AGENTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csJCJLsIFsaEaz8246HxM1O9esu6KWC1
"""

!pip install -q virtualenv
!virtualenv lc_env

# Install packages inside the environment
!./lc_env/bin/pip install -q langchain==0.2.16 \
    langchain-core==0.2.38 \
    langchain-community==0.2.7 \
    langchain-openai \
    langchain-google-genai \
    duckduckgo-search \
    requests

import sys
sys.path.insert(0, "/content/lc_env/lib/python3.12/site-packages")

import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyDwOLIygA"

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
import requests

import warnings
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", category=UserWarning)

from langchain_community.tools import DuckDuckGoSearchRun

search_tool = DuckDuckGoSearchRun()

result = search_tool.run("What is the top news in India today?")
print(result)

llm=ChatGoogleGenerativeAI(model="gemini-pro")

from langchain.agents import create_react_agent, AgentExecutor
from langchain import hub

import warnings
import os

# Ignore the specific DeprecationWarning from jupyter_client
warnings.filterwarnings("ignore", message="datetime.datetime.utcnow() is deprecated")

# Disable LangSmith tracing
os.environ["LANGCHAIN_TRACING_V2"] = "false"

# Step 2: Pull the ReAct prompt from LangChain Hub
prompt = hub.pull("hwchase17/react")  # pulls the standard ReAct agent prompt

# Step 3: Create the ReAct agent manually with the pulled prompt
agent = create_react_agent(
    llm=llm,
    tools=[search_tool, get_weather_data],
    prompt=prompt
)

# Step 4: Wrap it with AgentExecutor
agent_executor = AgentExecutor(
    agent=agent,
    tools=[search_tool, get_weather_data],
    verbose=True
)

# Step 5: Invoke
response = agent_executor.invoke({"input": "Find the capital of Madhya Pradesh, then find it's current weather condition"})
print(response)

response['output']