# -*- coding: utf-8 -*-
"""vector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Tp5UUfI1Fz5bx-Gnz9CPgjcsyDq9cza
"""

import os
os.environ["GEMINI_API_KEY"] = "sk-proj-"

!pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community langchain-google-genai

from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain.vectorstores import chroma

from langchain.schema import Document

# Create LangChain documents for IPL players

doc1 = Document(
        page_content="Virat Kohli is one of the most successful and consistent batsmen in IPL history. Known for his aggressive batting style and fitness, he has led the Royal Challengers Bangalore in multiple seasons.",
        metadata={"team": "Royal Challengers Bangalore"}
    )
doc2 = Document(
        page_content="Rohit Sharma is the most successful captain in IPL history, leading Mumbai Indians to five titles. He's known for his calm demeanor and ability to play big innings under pressure.",
        metadata={"team": "Mumbai Indians"}
    )
doc3 = Document(
        page_content="MS Dhoni, famously known as Captain Cool, has led Chennai Super Kings to multiple IPL titles. His finishing skills, wicketkeeping, and leadership are legendary.",
        metadata={"team": "Chennai Super Kings"}
    )
doc4 = Document(
        page_content="Jasprit Bumrah is considered one of the best fast bowlers in T20 cricket. Playing for Mumbai Indians, he is known for his yorkers and death-over expertise.",
        metadata={"team": "Mumbai Indians"}
    )
doc5 = Document(
        page_content="Ravindra Jadeja is a dynamic all-rounder who contributes with both bat and ball. Representing Chennai Super Kings, his quick fielding and match-winning performances make him a key player.",
        metadata={"team": "Chennai Super Kings"}
    )

docs = [doc1, doc2, doc3, doc4, doc5]

from collections.abc import Collection
vector_store = chroma.Chroma(
    embedding_function=GoogleGenerativeAIEmbeddings(model="models/embedding-001"),
    persist_directory="./chroma_db",
    collection_name="sample"
)

# adding documents
vector_store.add_documents(docs)

