# -*- coding: utf-8 -*-
"""built in tools .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOMCxFxtr1qp-zVbbKQrqrIOzpifqlP_
"""

pip install langchain langchain-core langchain-community pydantic duckduckgo-search langchain_experimental

"""DUCK DUCK GO

"""

print(search_tool.name)
print(search_tool.description)
print(search_tool.args)

"""SHELL TOOL

"""

from langchain.tools import ShellTool
shell_tool = ShellTool()

result=shell_tool.invoke({"commands": ["ls", "pwd"]})
print(result)

"""CUSTOM TOOLS"""

from langchain_community.tools import tool

# creating a fucntion
def multiply(a,b):
  """Multiply two numnbers"""
  return a*b

# type hints
def multiply(a: int ,b : int )-> int :
  """Multiply two numnbers"""
  return a*b

# tools decoratoor
@tool
def multiply(a: int ,b : int )-> int :
  """Multiply two numnbers"""
  return a*b

result=multiply.invoke({"a":3,"b":5})

print(result)

print(multiply.name)
print(multiply.description)
print(multiply.args)

print(multiply.args_schema.model_json_schema())

"""Structured tools"""

from langchain.tools import StructuredTool
from pydantic import BaseModel, Field

class MultiplyInput(BaseModel):
  a: int = Field(description="first number")
  b: int = Field(description="second number")

def multiply_func(a :int , b:int) -> int :
  return a*b

multiply_tool=StructuredTool.from_function(
    func=multiply_func,
    name="Multiply",
    description="Multiply two numbers",
    args_schema=MultiplyInput
)

result=multiply_tool.invoke({"a":3,"b":5})
print(result)
print(multiply_tool.name)
print(multiply_tool.description)
print(multiply_tool.args)

"""BASE TOOLS CLASS"""

from langchain.tools import BaseTool
from typing import Type

# args schema using pydantic

class MultiplyInput(BaseModel):
    a: int = Field(required=True, description="The first number to add")
    b: int = Field(required=True, description="The second number to add")

class MultiplyTool(BaseTool):
    name: str = "multiply"
    description: str = "Multiply two numbers"

    args_schema: Type[BaseModel] = MultiplyInput

    def _run(self, a: int, b: int) -> int:
        return a * b

multiply_tool = MultiplyTool()

result = multiply_tool.invoke({'a':3, 'b':3})

print(result)
print(multiply_tool.name)
print(multiply_tool.description)

print(multiply_tool.args)

"""tool kit"""

from langchain_core.tools import tool

# Custom tools
@tool
def add(a: int, b: int) -> int:
    """Add two numbers"""
    return a + b

@tool
def multiply(a: int, b: int) -> int:
    """Multiply two numbers"""
    return a * b

class MathToolkit:
    def get_tools(self):
        return [add, multiply]

toolkit = MathToolkit()
tools = toolkit.get_tools()

for tool in tools:
    print(tool.name, "=>", tool.description)

